### ISSUE TITLE
Include npm

### ISSUE THREAD

**Issue by jo** [hoodiehq/spawn-pouchdb-server#4]
Currently the path to the pouchdb-server bin [is hardcoded](https://github.com/gr2m/spawn-pouchdb-server/blob/master/index.js#L24).

But when used in a project which already includes pouchdb-server the dependency is not double installed and taken from there. Also, npm v3 has flat dependencies so it might break.

The solution is to [ask npm for the executable path](https://github.com/npm/npm#using-npm-programmatically). If in doubt, I'm sure @boennemann can help ;)

**Comment by jo** [comment]
For example in my case the location is `'../../../../node_modules/.bin/pouchdb-server'`

**Comment by boennemann** [comment]
You could use [require-relative](https://github.com/kamicane/require-relative) and resolve the path to pouchdb-server relative to the cwd. If that doesn't find anything you just use the one you're bundling.

**Comment by gr2m** [comment]
I tried `require.resolve('pouchdb-server')` but didn't work for some reason. I'll try to get something working with require-relative, but really don't know how to solve this right now

**Comment by boennemann** [comment]
I now know why `require.resolve('pouchdb-server')` didn't work for you. It doesn't have a main entry in the `package.json` and no `index.js`. Generally the work around here is to do `path.dirname(require.resolve('pouchdb-server/package.json'))` so you get the root folder of the package.

I'm sending a PR to address both this and the original issue by @jo.
